package binery.tree;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Farzad
 */
public class IP_Address_Lookup extends javax.swing.JFrame {

    /**
     * Creates new form Main_Fram
     */
    public IP_Address_Lookup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ComboBox1 = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Mac = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        O_3 = new javax.swing.JTextField();
        O_4 = new javax.swing.JTextField();
        O_1 = new javax.swing.JTextField();
        O_2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ip = new javax.swing.JTable();

        jFormattedTextField1.setText("jFormattedTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Switch & Router ");
        setBackground(new java.awt.Color(204, 204, 255));

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Binary Trie", "Subtree-Split", "Level Compression Trie", "Bitmap tree " }));
        ComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });

        addButton.setText("Add IP");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("/");

        Mac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MacKeyPressed(evt);
            }
        });

        Search.setText("Search IP");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jLabel4.setText("Search:");

        O_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                O_3KeyPressed(evt);
            }
        });

        O_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                O_4KeyPressed(evt);
            }
        });

        O_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                O_1KeyPressed(evt);
            }
        });

        O_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                O_2KeyPressed(evt);
            }
        });

        table_ip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ip", "sub", "port"
            }
        ));
        jScrollPane1.setViewportView(table_ip);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(O_1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(O_2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(O_3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(O_4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(Mac, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(ComboBox1, 0, 234, Short.MAX_VALUE))
                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(O_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(O_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(O_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(O_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       BT bt = new BT();
    bin b = new bin();
    Object[] row = new Object[3];
    int flag = 1;
    BinaryTree tree = new BinaryTree();
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (flag == 1) {
            String[] s = null;
            String ip = "";
            try {
                JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
                FileFilter text = new FileNameExtensionFilter("Text file", "txt");
                jfc.setFileFilter(text);
                jfc.setAcceptAllFileFilterUsed(false);
                jfc.setDialogTitle("Open a file(.txt)");
                int returnValue = jfc.showOpenDialog(null);

                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = jfc.getSelectedFile();
                    File file = new File(selectedFile.getAbsolutePath());
                    if (file.exists()) {
                        flag = 0;
                        BufferedReader bu = new BufferedReader(new FileReader(file));
                        String line;
                        while ((line = bu.readLine()) != null) {
                            s = null;
                            s = line.split("/", 6);
                            b.bin(Integer.parseInt(s[0]));
                            ip += String.format("%8s", b.g()).replace(' ', '0');
                            b.Clear();
                            b.bin(Integer.parseInt(s[1]));
                            ip += String.format("%8s", b.g()).replace(' ', '0');
                            b.Clear();
                            b.bin(Integer.parseInt(s[2]));
                            ip += String.format("%8s", b.g()).replace(' ', '0');
                            b.Clear();
                            b.bin(Integer.parseInt(s[3]));
                            ip += String.format("%8s", b.g()).replace(' ', '0');
                            b.Clear();
                            int sub = Integer.parseInt(s[4]);
                            String ip1 = ip;
                            ip = ip.substring(0, sub);

                            bt.insert(ip, s[5]);
                            // Add bitmap
                            tree.insertIP(ip1, sub, s[5]);
                            //
                            ip = "";
                            ip1 = "";
                            DefaultTableModel model = (DefaultTableModel) table_ip.getModel();
                            model.addRow(new Object[]{s[0] + "." + s[1] + "." + s[2] + "." + s[3], s[4], s[5]});
                            ip = "";
                        }
                    } else {
                        System.out.println(file.getAbsoluteFile() + "\n  not exist");
                    }
                }

            } catch (FileNotFoundException e) {
            } catch (IOException ex) {
                Logger.getLogger(IP_Address_Lookup.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "ای پی ها قبلا ذخیره شدند.", "", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void MacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MacKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MacKeyPressed

    private void O_3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_O_3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_O_3KeyPressed

    private void O_4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_O_4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_O_4KeyPressed

    private void O_1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_O_1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_O_1KeyPressed

    private void O_2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_O_2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_O_2KeyPressed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        try {
            String ip = "";
            int Oct_1 = Integer.parseInt(O_1.getText());
            int Oct_2 = Integer.parseInt(O_2.getText());
            int Oct_3 = Integer.parseInt(O_3.getText());
            int Oct_4 = Integer.parseInt(O_4.getText());
            int S_mac = Integer.parseInt(Mac.getText());

            b.bin(Oct_1);
            String div1 = b.g();
            b.Clear();
            ip += String.format("%8s", div1).replace(' ', '0');
            b.bin(Oct_2);
            String div2 = b.g();
            b.Clear();
            ip += String.format("%8s", div2).replace(' ', '0');
            b.bin(Oct_3);
            String div3 = b.g();
            b.Clear();
            ip += String.format("%8s", div3).replace(' ', '0');
            b.bin(Oct_4);
            String div4 = b.g();
            b.Clear();
            ip += String.format("%8s", div4).replace(' ', '0');
            String ip1 = ip;
            ip = ip.substring(0, S_mac);

            if (ComboBox1.getSelectedItem().equals("Binary Trie")) {
                String re = bt.search_binery_tree(ip);
                System.out.println("Node found Algoritem:" + re);
                System.out.println("\n--------------------------------End Algoritem_Binery_tree--------------------------------");

                JOptionPane.showMessageDialog(null, "Search result from the algoritem Binery Trie:\n'" + "\t" + re + "'\n*implementation details (Binery_tree) in the output comment*");
            }

            if (ComboBox1.getSelectedItem().equals("Subtree-Split")) {
                bt.sub_te(ip);
                JOptionPane.showMessageDialog(null, "Search result from the algoritem & *implementation details (Subtree-Split) in the output comment*");
            }

            if (ComboBox1.getSelectedItem().equals("Level Compression Trie")) {
                String g = bt.le_te(ip);
                System.out.println("Node found Algoritem:" + g);
                JOptionPane.showMessageDialog(null, "Search result from the algoritem Level Compression Trie:\n'" + "\t" + g + "'\n*implementation details (Level Compression Trie) in the output comment*");
            }
            if (ComboBox1.getSelectedItem().equals("Bitmap tree ")) {
                String g = bt.Bit_map(ip1,tree);
               // TreeBitmap t = tree.getTreeBitmap();
                JOptionPane.showMessageDialog(null, "Search result from the algoritem Bitmap tree:\n'" + "\t" + g);

            }
        } catch (HeadlessException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "مشکل در ورودی اعداد وجود دارد", "", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_SearchActionPerformed

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IP_Address_Lookup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IP_Address_Lookup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IP_Address_Lookup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IP_Address_Lookup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IP_Address_Lookup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox1;
    private javax.swing.JTextField Mac;
    private javax.swing.JTextField O_1;
    private javax.swing.JTextField O_2;
    private javax.swing.JTextField O_3;
    private javax.swing.JTextField O_4;
    private javax.swing.JButton Search;
    private javax.swing.JButton addButton;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable table_ip;
    // End of variables declaration//GEN-END:variables
}
